apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace }}
data:
  PROFILES_SERVICE_URL: "http://profiles-service:80"
  MATCHER_SERVICE_URL: "http://matcher-service:80"
  REDIS_URL: "redis://redis:6379"
  DATABASE_URL: "postgresql://{{ .Values.postgres.credentials.user }}:{{ .Values.postgres.credentials.password }}@postgres:5432/{{ .Values.postgres.credentials.database }}"
