<script setup>
import { ref, onMounted } from 'vue'

// throw new Error; to check if app.config console.log errorHandler works
const msg = ref('SHUT UP');

const rawHtml = ref('<span style="color: red">This should be red.</span>');

const someId = ref('elementId');

const id = ref('elementId');

const isButtonDisabled = ref(true); // or function isButtonDisabled() { return true };

const elementAttrs = {
  id: 'idValue',
  class: 'classValue',
  style: 'background-color:green',
};

const date = new Date("December 17, 1995 03:24:00");
function toDateTitle(date) {
  return 'dateTitle';
}
function formattedDate(date) {
  return date.toString();
}

const show = ref(true);

function changeMsgValue(newValue) {
  msg.value = newValue;
}

const attributeName = ref('hm');
const url = ref('some.link');
function setAttributeName() {
  attributeName.value = 'href';
}

onMounted(() => {
  setAttributeName()
})

</script>

<template>
    <p>{{ msg }}</p>
    <p>Using text interpolation: {{ rawHtml }}</p>
    <p>Using v-html directive: <span v-html="rawHtml"></span></p>
    <p :id='someId'>This element has a dynamic id</p>
    <p :id>This element has a dynamic id and uses a :id sugar</p>
    <button :disabled="isButtonDisabled">This button can be disabled dynamically</button>
    <div :='elementAttrs'>This div has attributes set dynamically from an object of attributes</div>
    <div :id='`div-${id}`'>This div has Js expressions (not statements!) in {{ 'mustaches'.split('') }}  and directives</div>
    <time :title='toDateTitle(date)' :datetime='date'>This time is dynamically generated by calling a method {{ formattedDate(date) }}</time>
    <p v-if='show'>This element is rendered conditionally</p>
    <button @click="changeMsgValue('SCREAM!!!')">This button calls a method on click</button>
    <a :[attributeName]='url'>This element has a dynamically set dynamically decided attribute</a>
    <form @submit.prevent='onSubmit'>This form prevents default on submission</form>
</template>

<style scoped>

</style>
