apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
